// Auto-generated Bansuri Ecommerce Product Catalogue Data
// Generated by Automated Asset Pipeline Architect

export interface ProductSizeOption {
  size: string;
  mrp: number;
  b2bPrice: number;
}

export interface Product {
  id: string;
  name: string;
  category: string;
  categoryName: string;
  variantName: string;
  price: number;
  b2bPrice: number;
  minB2bQty: number;
  unit: string;
  sizes: ProductSizeOption[];
  isBestseller: boolean;
  isNew: boolean;
  image: string;
  webpImage: string;
  thumbImage: string;
  gstRate: number;
  description: string;
}

export const PRODUCT_CATALOGUE_DATA: Product[] = [
  {
    "id": "bansuri-packet-classic-19",
    "name": "Bansuri Agarbathi Classic (19g)",
    "category": "packet-series",
    "categoryName": "Packet Series",
    "variantName": "Bansuri",
    "price": 15,
    "b2bPrice": 11,
    "minB2bQty": 100,
    "unit": "19g",
    "sizes": [
      {
        "size": "19g",
        "mrp": 15,
        "b2bPrice": 11
      },
      {
        "size": "60g",
        "mrp": 45,
        "b2bPrice": 34
      },
      {
        "size": "120g",
        "mrp": 75,
        "b2bPrice": 56
      }
    ],
    "isBestseller": true,
    "isNew": false,
    "image": "/assets/images/products/packet-series/packet-series-classic-19.png",
    "webpImage": "/assets/images/products/packet-series/packet-series-classic-19.webp",
    "thumbImage": "/assets/images/products/packet-series/packet-series-classic-19-thumb.webp",
    "gstRate": 12,
    "description": "Traditional aromatic incense sticks crafted with natural herbs and pure sandalwood extract."
  },
  {
    "id": "bansuri-packet-classic-120",
    "name": "Bansuri Agarbathi Classic (120g)",
    "category": "packet-series",
    "categoryName": "Packet Series",
    "variantName": "Bansuri",
    "price": 45,
    "b2bPrice": 34,
    "minB2bQty": 50,
    "unit": "60g",
    "sizes": [
      {
        "size": "60g",
        "mrp": 45,
        "b2bPrice": 34
      },
      {
        "size": "120g",
        "mrp": 75,
        "b2bPrice": 56
      },
      {
        "size": "250g",
        "mrp": 140,
        "b2bPrice": 105
      }
    ],
    "isBestseller": true,
    "isNew": false,
    "image": "/assets/images/products/packet-series/packet-series-classic-120.png",
    "webpImage": "/assets/images/products/packet-series/packet-series-classic-120.webp",
    "thumbImage": "/assets/images/products/packet-series/packet-series-classic-120-thumb.webp",
    "gstRate": 12,
    "description": "Value pack classic agarbathi for daily devotional prayers and soothing home fragrance."
  },
  {
    "id": "bansuri-packet-vibe-120",
    "name": "Bansuri Agarbathi Vibe (120g)",
    "category": "packet-series",
    "categoryName": "Packet Series",
    "variantName": "Bansuri",
    "price": 30,
    "b2bPrice": 22,
    "minB2bQty": 60,
    "unit": "42g",
    "sizes": [
      {
        "size": "42g",
        "mrp": 30,
        "b2bPrice": 22
      },
      {
        "size": "120g",
        "mrp": 75,
        "b2bPrice": 56
      }
    ],
    "isBestseller": false,
    "isNew": true,
    "image": "/assets/images/products/packet-series/packet-series-vibe-120.png",
    "webpImage": "/assets/images/products/packet-series/packet-series-vibe-120.webp",
    "thumbImage": "/assets/images/products/packet-series/packet-series-vibe-120-thumb.webp",
    "gstRate": 12,
    "description": "Energetic blend of modern floral and spicy notes designed for modern living spaces."
  },
  {
    "id": "bansuri-packet-pineapple-42",
    "name": "Bansuri Agarbathi Pineapple (42g)",
    "category": "packet-series",
    "categoryName": "Packet Series",
    "variantName": "Bansuri",
    "price": 25,
    "b2bPrice": 18,
    "minB2bQty": 80,
    "unit": "42g",
    "sizes": [
      {
        "size": "42g",
        "mrp": 25,
        "b2bPrice": 18
      },
      {
        "size": "100g",
        "mrp": 60,
        "b2bPrice": 45
      }
    ],
    "isBestseller": false,
    "isNew": false,
    "image": "/assets/images/products/packet-series/packet-series-pineapple-42.png",
    "webpImage": "/assets/images/products/packet-series/packet-series-pineapple-42.webp",
    "thumbImage": "/assets/images/products/packet-series/packet-series-pineapple-42-thumb.webp",
    "gstRate": 12,
    "description": "Sweet fruity pineapple fragrance offering a refreshing and uplifting atmosphere."
  },
  {
    "id": "bansuri-packet-mogra-19",
    "name": "Bansuri Agarbathi Mogra (19g)",
    "category": "packet-series",
    "categoryName": "Packet Series",
    "variantName": "Bansuri",
    "price": 15,
    "b2bPrice": 11,
    "minB2bQty": 100,
    "unit": "19g",
    "sizes": [
      {
        "size": "19g",
        "mrp": 15,
        "b2bPrice": 11
      },
      {
        "size": "60g",
        "mrp": 45,
        "b2bPrice": 34
      },
      {
        "size": "120g",
        "mrp": 75,
        "b2bPrice": 56
      }
    ],
    "isBestseller": false,
    "isNew": false,
    "image": "/assets/images/products/packet-series/packet-series-mogra-19.png",
    "webpImage": "/assets/images/products/packet-series/packet-series-mogra-19.webp",
    "thumbImage": "/assets/images/products/packet-series/packet-series-mogra-19-thumb.webp",
    "gstRate": 12,
    "description": "Intense fresh jasmine mogra incense sticks for evening rituals and meditation."
  },
  {
    "id": "bansuri-packet-lavender-120",
    "name": "Bansuri Agarbathi Lavender (120g)",
    "category": "packet-series",
    "categoryName": "Packet Series",
    "variantName": "Bansuri",
    "price": 45,
    "b2bPrice": 34,
    "minB2bQty": 50,
    "unit": "60g",
    "sizes": [
      {
        "size": "60g",
        "mrp": 45,
        "b2bPrice": 34
      },
      {
        "size": "120g",
        "mrp": 75,
        "b2bPrice": 56
      }
    ],
    "isBestseller": false,
    "isNew": false,
    "image": "/assets/images/products/packet-series/packet-series-lavender-120.png",
    "webpImage": "/assets/images/products/packet-series/packet-series-lavender-120.webp",
    "thumbImage": "/assets/images/products/packet-series/packet-series-lavender-120-thumb.webp",
    "gstRate": 12,
    "description": "Calming French lavender fragrance engineered to relax minds and reduce stress."
  },
  {
    "id": "bansuri-packet-chandan-19",
    "name": "Bansuri Agarbathi Chandan (19g)",
    "category": "packet-series",
    "categoryName": "Packet Series",
    "variantName": "Bansuri",
    "price": 15,
    "b2bPrice": 11,
    "minB2bQty": 100,
    "unit": "19g",
    "sizes": [
      {
        "size": "19g",
        "mrp": 15,
        "b2bPrice": 11
      },
      {
        "size": "60g",
        "mrp": 45,
        "b2bPrice": 34
      },
      {
        "size": "120g",
        "mrp": 75,
        "b2bPrice": 56
      }
    ],
    "isBestseller": true,
    "isNew": false,
    "image": "/assets/images/products/packet-series/packet-series-chandan-19.png",
    "webpImage": "/assets/images/products/packet-series/packet-series-chandan-19.webp",
    "thumbImage": "/assets/images/products/packet-series/packet-series-chandan-19-thumb.webp",
    "gstRate": 12,
    "description": "Pure Mysore sandalwood aroma delivering sacred ambiance during pujas and festivals."
  },
  {
    "id": "bansuri-premium-packet-royal",
    "name": "Bansuri Royal Agarbathi (100g)",
    "category": "premium-packet-series",
    "categoryName": "Premium Packet Series",
    "variantName": "Bansuri",
    "price": 90,
    "b2bPrice": 68,
    "minB2bQty": 40,
    "unit": "100g",
    "sizes": [
      {
        "size": "100g",
        "mrp": 90,
        "b2bPrice": 68
      },
      {
        "size": "250g",
        "mrp": 210,
        "b2bPrice": 158
      }
    ],
    "isBestseller": true,
    "isNew": true,
    "image": "/assets/images/products/premium-packet-series/premium-packet-royal.png",
    "webpImage": "/assets/images/products/premium-packet-series/premium-packet-royal.webp",
    "thumbImage": "/assets/images/products/premium-packet-series/premium-packet-royal-thumb.webp",
    "gstRate": 12,
    "description": "Luxury royal blend with natural essential oils and hand-rolled charcoal base."
  },
  {
    "id": "bansuri-special-beats-45",
    "name": "Bansuri Special Beats (45g)",
    "category": "special-series",
    "categoryName": "Special Series",
    "variantName": "Bansuri",
    "price": 35,
    "b2bPrice": 26,
    "minB2bQty": 60,
    "unit": "45g",
    "sizes": [
      {
        "size": "45g",
        "mrp": 35,
        "b2bPrice": 26
      },
      {
        "size": "100g",
        "mrp": 75,
        "b2bPrice": 56
      }
    ],
    "isBestseller": true,
    "isNew": false,
    "image": "/assets/images/products/special-series/special-beats-45.png",
    "webpImage": "/assets/images/products/special-series/special-beats-45.webp",
    "thumbImage": "/assets/images/products/special-series/special-beats-45-thumb.webp",
    "gstRate": 12,
    "description": "Special fusion formula with vibrant aromatic spices and sweet floral resins."
  },
  {
    "id": "bansuri-pouch-classic",
    "name": "Bansuri Zipper Pouch Classic (250g)",
    "category": "pouch-series",
    "categoryName": "Pouch Series",
    "variantName": "Bansuri",
    "price": 140,
    "b2bPrice": 105,
    "minB2bQty": 30,
    "unit": "250g",
    "sizes": [
      {
        "size": "250g",
        "mrp": 140,
        "b2bPrice": 105
      },
      {
        "size": "500g",
        "mrp": 260,
        "b2bPrice": 195
      }
    ],
    "isBestseller": true,
    "isNew": false,
    "image": "/assets/images/products/pouch-series/pouch-classic.png",
    "webpImage": "/assets/images/products/pouch-series/pouch-classic.webp",
    "thumbImage": "/assets/images/products/pouch-series/pouch-classic-thumb.webp",
    "gstRate": 12,
    "description": "Resealable zipper pouch preserving freshness of classic incense sticks for months."
  },
  {
    "id": "bansuri-wet-classic",
    "name": "Bansuri Classic Wet Dhoop",
    "category": "wet-dhoop",
    "categoryName": "Wet Dhoop",
    "variantName": "Bansuri",
    "price": 15,
    "b2bPrice": 11,
    "minB2bQty": 100,
    "unit": "50g",
    "sizes": [
      {
        "size": "50g",
        "mrp": 15,
        "b2bPrice": 11
      },
      {
        "size": "100g",
        "mrp": 30,
        "b2bPrice": 22
      }
    ],
    "isBestseller": true,
    "isNew": false,
    "image": "/assets/images/products/wet-dhoop/wet-dhoop-classic.png",
    "webpImage": "/assets/images/products/wet-dhoop/wet-dhoop-classic.webp",
    "thumbImage": "/assets/images/products/wet-dhoop/wet-dhoop-classic-thumb.webp",
    "gstRate": 12,
    "description": "Pliable traditional wet dhoop sticks producing dense aromatic smoke."
  },
  {
    "id": "bansuri-solid-guggal",
    "name": "Bansuri Guggal Solid Dhoop (100g)",
    "category": "solid-dhoop",
    "categoryName": "Solid Dhoop",
    "variantName": "Bansuri",
    "price": 50,
    "b2bPrice": 38,
    "minB2bQty": 60,
    "unit": "100g",
    "sizes": [
      {
        "size": "100g",
        "mrp": 50,
        "b2bPrice": 38
      }
    ],
    "isBestseller": true,
    "isNew": false,
    "image": "/assets/images/products/solid-dhoop/solid-dhoop-guggal.png",
    "webpImage": "/assets/images/products/solid-dhoop/solid-dhoop-guggal.webp",
    "thumbImage": "/assets/images/products/solid-dhoop/solid-dhoop-guggal-thumb.webp",
    "gstRate": 12,
    "description": "Pure unadulterated guggal resin dhoop sticks for purifying home environment."
  },
  {
    "id": "bansuri-sambrani-cup-12",
    "name": "Bansuri Special Cup Sambrani (12N)",
    "category": "sambrani",
    "categoryName": "Sambrani",
    "variantName": "Bansuri",
    "price": 72,
    "b2bPrice": 54,
    "minB2bQty": 40,
    "unit": "12N",
    "sizes": [
      {
        "size": "12N",
        "mrp": 72,
        "b2bPrice": 54
      }
    ],
    "isBestseller": true,
    "isNew": true,
    "image": "/assets/images/products/sambrani/sambrani-special-cup.png",
    "webpImage": "/assets/images/products/sambrani/sambrani-special-cup.webp",
    "thumbImage": "/assets/images/products/sambrani/sambrani-special-cup-thumb.webp",
    "gstRate": 12,
    "description": "Ready-to-use charcoal cups filled with natural benzoin sambrani resin and herbs."
  },
  {
    "id": "bansuri-sambrani-cones-10",
    "name": "Bansuri Cones Sambrani (10N)",
    "category": "sambrani",
    "categoryName": "Sambrani",
    "variantName": "Bansuri",
    "price": 15,
    "b2bPrice": 11,
    "minB2bQty": 100,
    "unit": "10N",
    "sizes": [
      {
        "size": "10N",
        "mrp": 15,
        "b2bPrice": 11
      }
    ],
    "isBestseller": true,
    "isNew": false,
    "image": "/assets/images/products/sambrani/sambrani-cones.png",
    "webpImage": "/assets/images/products/sambrani/sambrani-cones.webp",
    "thumbImage": "/assets/images/products/sambrani/sambrani-cones-thumb.webp",
    "gstRate": 12,
    "description": "Dense aromatic sambrani incense cones with ceramic burner stand included."
  },
  {
    "id": "bansuri-sambrani-sticks-10",
    "name": "Bansuri Sambrani Dhoop (10N & 15N)",
    "category": "sambrani",
    "categoryName": "Sambrani",
    "variantName": "Bansuri",
    "price": 15,
    "b2bPrice": 11,
    "minB2bQty": 100,
    "unit": "10N",
    "sizes": [
      {
        "size": "10N",
        "mrp": 15,
        "b2bPrice": 11
      },
      {
        "size": "15N",
        "mrp": 25,
        "b2bPrice": 18
      }
    ],
    "isBestseller": true,
    "isNew": false,
    "image": "/assets/images/products/sambrani/sambrani-sticks.png",
    "webpImage": "/assets/images/products/sambrani/sambrani-sticks.webp",
    "thumbImage": "/assets/images/products/sambrani/sambrani-sticks-thumb.webp",
    "gstRate": 12,
    "description": "Traditional cylindrical sambrani dhoop sticks offering continuous slow burn."
  },
  {
    "id": "bansuri-sambrani-rose-10",
    "name": "Bansuri Cones Rose (10N)",
    "category": "sambrani",
    "categoryName": "Sambrani",
    "variantName": "Bansuri",
    "price": 15,
    "b2bPrice": 11,
    "minB2bQty": 100,
    "unit": "10N",
    "sizes": [
      {
        "size": "10N",
        "mrp": 15,
        "b2bPrice": 11
      }
    ],
    "isBestseller": false,
    "isNew": false,
    "image": "/assets/images/products/sambrani/sambrani-rose-cones.png",
    "webpImage": "/assets/images/products/sambrani/sambrani-rose-cones.webp",
    "thumbImage": "/assets/images/products/sambrani/sambrani-rose-cones-thumb.webp",
    "gstRate": 12,
    "description": "Rose infused aromatic incense cones delivering delightful floral fragrance."
  },
  {
    "id": "bansuri-sambrani-chandan-10",
    "name": "Bansuri Cones Chandan (10N)",
    "category": "sambrani",
    "categoryName": "Sambrani",
    "variantName": "Bansuri",
    "price": 15,
    "b2bPrice": 11,
    "minB2bQty": 100,
    "unit": "10N",
    "sizes": [
      {
        "size": "10N",
        "mrp": 15,
        "b2bPrice": 11
      }
    ],
    "isBestseller": false,
    "isNew": false,
    "image": "/assets/images/products/sambrani/sambrani-chandan-cones.png",
    "webpImage": "/assets/images/products/sambrani/sambrani-chandan-cones.webp",
    "thumbImage": "/assets/images/products/sambrani/sambrani-chandan-cones-thumb.webp",
    "gstRate": 12,
    "description": "Sandalwood scented sambrani cones providing serene spiritual atmosphere."
  },
  {
    "id": "vasu-agarbathi-60",
    "name": "Vasu Premium Agarbathi (60g)",
    "category": "vasu",
    "categoryName": "Vasu",
    "variantName": "Vasu",
    "price": 50,
    "b2bPrice": 38,
    "minB2bQty": 50,
    "unit": "60g",
    "sizes": [
      {
        "size": "60g",
        "mrp": 50,
        "b2bPrice": 38
      },
      {
        "size": "108g",
        "mrp": 95,
        "b2bPrice": 71
      }
    ],
    "isBestseller": true,
    "isNew": false,
    "image": "/assets/images/products/vasu/vasu-60.png",
    "webpImage": "/assets/images/products/vasu/vasu-60.webp",
    "thumbImage": "/assets/images/products/vasu/vasu-60-thumb.webp",
    "gstRate": 12,
    "description": "Iconic Vasu series featuring ancient Vedic herbs and rare aromatic bark oils."
  },
  {
    "id": "bansuri-hexa-classic",
    "name": "Bansuri Hexa Pack Classic",
    "category": "hexa",
    "categoryName": "Hexa",
    "variantName": "Bansuri",
    "price": 60,
    "b2bPrice": 45,
    "minB2bQty": 60,
    "unit": "100g",
    "sizes": [
      {
        "size": "100g",
        "mrp": 60,
        "b2bPrice": 45
      }
    ],
    "isBestseller": true,
    "isNew": false,
    "image": "/assets/images/products/hexa/hexa-classic.png",
    "webpImage": "/assets/images/products/hexa/hexa-classic.webp",
    "thumbImage": "/assets/images/products/hexa/hexa-classic-thumb.webp",
    "gstRate": 12,
    "description": "Hexagonal export pack of premium hand-rolled incense sticks."
  }
];

export default PRODUCT_CATALOGUE_DATA;
